export const SET_USER = 'SET_USER'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'

export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const GET_PONTOSHISTORICOS= 'GET_PONTOSHISTORICOS'
export const GET_PONTOHISTORICO= 'GET_PONTOHISTORICO'
export const CLEAR_PONTOHISTORICO = 'CLEAR_PONTOHISTORICO'